In [ ]:
import argparse
import os
import numpy as np
import torchvision
import torchvision.transforms as transforms
from torchvision import datasets
from torch.utils.data import Dataset

In [ ]:
print("cifar10"+ "*"*100)
train_transform = transforms.Compose([transforms.ToTensor()])
train_set = torchvision.datasets.CIFAR10(root="./cifar10", train=True, download=True, transform=train_transform)
print(train_set)
print(train_set.data.shape)
print("mean:")
print(np.mean(train_set.data, axis=(0,1,2))/255)
print("std:")
print(np.std(train_set.data, axis=(0,1,2))/255)
print("*"*100)

cifar10****************************************************************************************************
Files already downloaded and verified
Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./cifar10
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
           )
(50000, 32, 32, 3)
mean:
[0.49139968 0.48215841 0.44653091]
std:
[0.24703223 0.24348513 0.26158784]
****************************************************************************************************


In [ ]:
!curl https://www.cs.toronto.edu/~kriz/cifar-100-python.tar.gz -o ./cifar100/cifar-100-python.tar.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  161M  100  161M    0     0  56.8M      0  0:00:02  0:00:02 --:--:-- 56.7M


In [ ]:
print("cifar100"+ "*"*100)
train_set = torchvision.datasets.CIFAR100(root="./cifar100", train=True, download=True, transform=train_transform)
print(train_set)
print(train_set.data.shape)
print("mean:")
print(np.mean(train_set.data, axis=(0,1,2))/255)
print("std:")
print(np.std(train_set.data, axis=(0,1,2))/255)
print("*"*100)

cifar100****************************************************************************************************
Files already downloaded and verified
Dataset CIFAR100
    Number of datapoints: 50000
    Root location: ./cifar100
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
           )
(50000, 32, 32, 3)
mean:
[0.50707516 0.48654887 0.44091784]
std:
[0.26733429 0.25643846 0.27615047]
****************************************************************************************************


In [ ]:
!curl https://ossci-datasets.s3.amazonaws.com/mnist/train-images-idx3-ubyte.gz -o ./mnist/MNIST/raw/train-images-idx3-ubyte.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 9680k  100 9680k    0     0  60.5M      0 --:--:-- --:--:-- --:--:-- 60.5M


In [ ]:
!curl https://ossci-datasets.s3.amazonaws.com/mnist/train-labels-idx1-ubyte.gz -o ./mnist/MNIST/raw/train-labels-idx1-ubyte.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28881  100 28881    0     0   433k      0 --:--:-- --:--:-- --:--:--  433k


In [ ]:
!curl https://ossci-datasets.s3.amazonaws.com/mnist/t10k-images-idx3-ubyte.gz -o ./mnist/MNIST/raw/t10k-images-idx3-ubyte.gz

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1610k  100 1610k    0     0  37.4M      0 --:--:-- --:--:-- --:--:-- 37.4M


In [ ]:
!curl https://ossci-datasets.s3.amazonaws.com/mnist/t10k-labels-idx1-ubyte.gz -o ./mnist/MNIST/raw/t10k-labels-idx1-ubyte.gz


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4542  100  4542    0     0  96638      0 --:--:-- --:--:-- --:--:-- 98739


In [ ]:
# print(train_set)
# print(list(train_set.data.size()))

print("cifar100"+ "*"*100)
train_set = torchvision.datasets.MNIST(root='./mnist', train=True, download=True, transform=train_transform)
print(train_set)
print(train_set.data.shape)
print("mean:")
print((train_set.data.float().mean()/255).item())
print("std:")
print((train_set.data.float().std()/255).item())
print("*"*100)

cifar100****************************************************************************************************
Dataset MNIST
    Number of datapoints: 60000
    Root location: ./mnist
    Split: Train
    StandardTransform
Transform: Compose(
               ToTensor()
           )
torch.Size([60000, 28, 28])
mean:
0.13066047430038452
std:
0.30810779333114624
****************************************************************************************************


In [ ]:
_data = {
    'imagenet': {
        'mean': [0.485, 0.456, 0.406], # mean
        'std': [0.229, 0.224, 0.225], # std
    },
    'cifar10': {
        'mean': [0.49139968, 0.48215841, 0.44653091], # mean
        'std': [0.24703223, 0.24348513, 0.26158784], # std
    },
    'cifar100': {
        'mean': [0.50707516, 0.48654887, 0.44091784],
        'std': [0.26733429, 0.25643846, 0.27615047],
    },
    'mnist': {
        'mean': [0.13066047430038452],
        'std': [0.30810779333114624],
    },
}
def get_dataset_mean_std(dataset_name: str='') -> dict:
    # names = ['cifar10', 'cifar100', 'mnist']
    if dataset_name not in _data.keys():
        print(f"dataset available: {[i for i in _data.keys()]}")
        return None
    else:
        return _data[dataset_name]

In [ ]:
get_dataset_mean_std('cifar10')

{'mean': [0.49139968, 0.48215841, 0.44653091],
 'std': [0.24703223, 0.24348513, 0.26158784]}

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=fee2cac7-e9c0-4831-885c-c2404547b160' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>